package api

import (
	"net/http"

	"explorer/internal/umlgen"
	"explorer/pkg/eth/common"

	"github.com/go-chi/chi/v5"
)

// umlGenerator renders sol2uml class diagrams. Package-level so the binary
// lookup (SOL2UML_PATH / PATH) happens once rather than per request.
var umlGenerator = umlgen.New("")

// handleGetContractUML returns an SVG UML class diagram of a verified
// contract's Solidity source, generated by sol2uml. Mirrors the "View UML
// diagram" button Blockscout shows on the contract tab.
func (s *Server) handleGetContractUML(w http.ResponseWriter, r *http.Request) {
	address := chi.URLParam(r, "address")
	if !common.IsHexAddress(address) {
		http.Error(w, "invalid address", http.StatusBadRequest)
		return
	}
	address = common.HexToAddress(address).Hex()

	contract, err := s.provider.GetContract(r.Context(), address)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if contract == nil {
		http.Error(w, "contract not found", http.StatusNotFound)
		return
	}
	if !contract.IsVerified || contract.SourceCode == nil || *contract.SourceCode == "" {
		http.Error(w, "contract source code is not available; verify the contract first", http.StatusNotFound)
		return
	}

	name := ""
	if contract.ContractName != nil {
		name = *contract.ContractName
	}

	svg, err := umlGenerator.GenerateSVG(r.Context(), name, *contract.SourceCode)
	if err != nil {
		http.Error(w, "failed to generate UML diagram: "+err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "image/svg+xml")
	w.Header().Set("Cache-Control", "public, max-age=300")
	w.Write(svg)
}
