include version.mk

# Load .env if present (generated by scripts/stack-ports.sh for parallel stacks).
# Must come before the ?= defaults so .env values take precedence.
-include .env

DOCKER_REGISTRY ?= gatewayfm
IMAGE_PREFIX ?= block-explorer

.PHONY: dev dev-stop dev-destroy dev-logs dev-rebuild-backend
.PHONY: dev-multi dev-multi-stop dev-multi-destroy dev-multi-logs
.PHONY: run run-privacy stop destroy logs rebuild-backend dev-stack
.PHONY: standalone standalone-stop
.PHONY: version docker-build docker-build-api docker-build-public-api docker-build-frontend docker-build-dry-run
.PHONY: lint test build clean clean-build

# Default RPC URL (use host.docker.internal to reach host from Docker)
RPC_URL ?= http://privacy-proxy-anvil-1:8545
START_BLOCK ?= 0

# Port configuration
API_PORT ?= 8081
FRONTEND_PORT ?= 3001
POSTGRES_PORT ?= 5433
ANVIL_PORT ?= 8546
PUBLIC_API_PORT ?= 8082

# Branding override file (optional)
# Usage: make run BRAND=examples/branding/docker-compose.full.yml
#        make dev BRAND=examples/branding/docker-compose.minimal.yml
BRAND ?=
BRAND_FLAG := $(if $(BRAND),-f $(BRAND),)

export API_PORT FRONTEND_PORT POSTGRES_PORT ANVIL_PORT PUBLIC_API_PORT PROXY_NETWORK

# =============================================================================
# Dev Environment (Anvil local testnet)
# =============================================================================

# The dev stack layers docker-compose.indexer.yml on top of the base
# dev compose to bring up gateway-fm/chain-indexer locally. The
# override references `gatewayfm/chain-indexer:latest` and pulls are
# disabled — see README for the prerequisite build step in
# ../chain-indexer (`make docker-build`).
DEV_COMPOSE := -f docker-compose.dev.yml -f docker-compose.indexer.yml $(BRAND_FLAG)

dev:
	@if ! docker image inspect gatewayfm/chain-indexer:latest >/dev/null 2>&1; then \
		echo "ERROR: image 'gatewayfm/chain-indexer:latest' not found locally."; \
		echo "Build it first (prerequisite):"; \
		echo "  cd ../chain-indexer && make docker-build"; \
		exit 1; \
	fi
	@echo "Starting Block Explorer (dev mode with Anvil + chain-indexer)..."
	@echo ""
	docker compose $(DEV_COMPOSE) build
	docker compose $(DEV_COMPOSE) up -d
	@echo ""
	@echo "Waiting for services..."
	@for i in 1 2 3 4 5 6 7 8 9 10; do \
		if curl -s http://127.0.0.1:$(API_PORT)/api/stats >/dev/null 2>&1; then \
			break; \
		fi; \
		sleep 2; \
	done
	@echo ""
	@echo "Block Explorer (dev) is ready!"
	@echo ""
	@echo "  Explorer:   http://localhost:$(FRONTEND_PORT)"
	@echo "  API:        http://localhost:$(API_PORT)"
	@echo "  Public API: http://localhost:$(PUBLIC_API_PORT)"
	@echo "  Anvil RPC:  http://localhost:$(ANVIL_PORT)"
	@echo ""
	@echo "Test accounts (each with 10000 ETH):"
	@echo "  0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
	@echo "  Private Key: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
	@echo ""

dev-stop:
	@echo "Stopping dev stack..."
	docker compose $(DEV_COMPOSE) down --remove-orphans
	@echo "Done"

dev-destroy:
	@echo "Destroying dev stack (containers, volumes, and images)..."
	docker compose $(DEV_COMPOSE) down -v --remove-orphans --rmi local
	@echo "Done"

dev-logs:
	docker compose $(DEV_COMPOSE) logs -f

dev-rebuild-backend:
	docker compose $(DEV_COMPOSE) build --no-cache api && docker compose $(DEV_COMPOSE) up -d api

# =============================================================================
# Multi-Network Dev Stack (two Anvil chains side-by-side)
# =============================================================================
#
# Brings up two complete, independent stacks so the frontend's network
# switcher can navigate between them — mirrors how Blockscout runs in
# production (one deployment per chain).
#
#   Network A (chain id 31337): Frontend 3001  API 8081  Anvil 8546
#   Network B (chain id 31338): Frontend 3002  API 8091  Anvil 8556

MULTI_COMPOSE := -f docker-compose.multi.yml

dev-multi:
	@if ! docker image inspect gatewayfm/chain-indexer:latest >/dev/null 2>&1; then \
		echo "ERROR: image 'gatewayfm/chain-indexer:latest' not found locally."; \
		echo "Build it first (prerequisite):"; \
		echo "  cd ../chain-indexer && make docker-build"; \
		exit 1; \
	fi
	@echo "Starting Block Explorer (multi-network: 2 Anvil chains)..."
	@echo ""
	docker compose $(MULTI_COMPOSE) build
	docker compose $(MULTI_COMPOSE) up -d
	@echo ""
	@echo "Waiting for services..."
	@for i in 1 2 3 4 5 6 7 8 9 10; do \
		if curl -s http://127.0.0.1:8081/api/stats >/dev/null 2>&1 && \
		   curl -s http://127.0.0.1:8091/api/stats >/dev/null 2>&1; then \
			break; \
		fi; \
		sleep 2; \
	done
	@echo ""
	@echo "Multi-network dev stack is ready!"
	@echo ""
	@echo "  Network A (chain id 31337):"
	@echo "    Explorer:   http://localhost:3001"
	@echo "    API:        http://localhost:8081"
	@echo "    Public API: http://localhost:8082"
	@echo "    Anvil RPC:  http://localhost:8546"
	@echo ""
	@echo "  Network B (chain id 31338):"
	@echo "    Explorer:   http://localhost:3002"
	@echo "    API:        http://localhost:8091"
	@echo "    Public API: http://localhost:8092"
	@echo "    Anvil RPC:  http://localhost:8556"
	@echo ""
	@echo "Open either frontend — the navbar 'Networks' dropdown switches between them."
	@echo "Edit frontend/public/featured-networks.json to rename / add networks."
	@echo ""

dev-multi-stop:
	@echo "Stopping multi-network stack..."
	docker compose $(MULTI_COMPOSE) down --remove-orphans
	@echo "Done"

dev-multi-destroy:
	@echo "Destroying multi-network stack (containers, volumes, and images)..."
	docker compose $(MULTI_COMPOSE) down -v --remove-orphans --rmi local
	@echo "Done"

dev-multi-logs:
	docker compose $(MULTI_COMPOSE) logs -f

# =============================================================================
# Parallel Dev Stacks (worktrees)
# =============================================================================

# Start an isolated dev stack — auto-assigns offset ports so parallel stacks don't conflict.
# In the main checkout (block-explorer/), behaves identically to `make run-privacy`.
# In a worktree or differently-named directory, generates .env with offset ports.
dev-stack:
	@if [ ! -f .env ] && [ "$$(basename "$$(pwd)")" != "block-explorer" ]; then \
		./scripts/stack-ports.sh auto > .env; \
		echo "Generated .env with offset ports (worktree detected)"; \
	fi
	docker compose -f docker-compose.yml $(BRAND_FLAG) build
	START_BLOCK=$(START_BLOCK) docker compose -f docker-compose.yml $(BRAND_FLAG) up -d
	@echo ""
	@echo "Block Explorer is ready!"
	@echo ""
	@echo "  Explorer:   http://localhost:$(FRONTEND_PORT)"
	@echo "  API:        http://localhost:$(API_PORT)"
	@echo "  Public API: http://localhost:$(PUBLIC_API_PORT)"
	@echo "  DB:         localhost:$(POSTGRES_PORT)"
	@echo ""

# =============================================================================
# Production (external RPC)
# =============================================================================

run:
	@echo "Starting Block Explorer..."
	@echo "RPC URL: $(RPC_URL)"
	@echo ""
	docker compose -f docker-compose.yml $(BRAND_FLAG) build
	RPC_URL=$(RPC_URL) START_BLOCK=$(START_BLOCK) docker compose -f docker-compose.yml $(BRAND_FLAG) up -d
	@echo ""
	@echo "Waiting for services..."
	@for i in 1 2 3 4 5 6 7 8 9 10; do \
		if curl -s http://127.0.0.1:$(API_PORT)/api/stats >/dev/null 2>&1; then \
			break; \
		fi; \
		sleep 2; \
	done
	@echo ""
	@echo "Block Explorer is ready!"
	@echo ""
	@echo "  Explorer:   http://localhost:$(FRONTEND_PORT)"
	@echo "  API:        http://localhost:$(API_PORT)"
	@echo "  Public API: http://localhost:$(PUBLIC_API_PORT)"
	@echo ""

run-privacy:
	@echo "Starting Block Explorer with Privacy Proxy enabled..."
	@echo "  API  RPC: privacy-proxy-backend:8080 (proxy)"
	@echo "  Indexer RPC: privacy-proxy-anvil:8545 (direct, for indexing)"
	@echo ""
	docker compose -f docker-compose.yml -f docker-compose.privacy.yml $(BRAND_FLAG) build
	START_BLOCK=$(START_BLOCK) docker compose -f docker-compose.yml -f docker-compose.privacy.yml $(BRAND_FLAG) up -d
	@echo ""
	@echo "Waiting for services..."
	@for i in 1 2 3 4 5 6 7 8 9 10; do \
		if curl -s http://127.0.0.1:$(API_PORT)/api/stats >/dev/null 2>&1; then \
			break; \
		fi; \
		sleep 2; \
	done
	@echo ""
	@echo "Block Explorer is ready! (Privacy ENABLED)"
	@echo ""
	@echo "  Explorer:  http://localhost:$(FRONTEND_PORT)"
	@echo "  API:       http://localhost:$(API_PORT)"
	@echo ""

# =============================================================================
# Standalone (production-style: bundled anvil + chain-indexer + indexer-postgres)
# =============================================================================
# Brings up the full self-contained stack for local / dev-style runs.
# The prod compose file (docker-compose.prod.yml) hard-requires its env
# vars (DATABASE_URL, RPC_URL, INDEXER_POSTGRES_PASSWORD) so a raw
# `docker compose ... up` cannot accidentally start with insecure dev
# defaults in a production deployment. This Makefile target sets those
# defaults explicitly so `make standalone` works OOTB locally; any
# value already in the environment wins via shell `:-`.
STANDALONE_COMPOSE := -f docker-compose.yml -f docker-compose.prod.yml $(BRAND_FLAG)
STANDALONE_DEFAULT_DB := postgres://postgres:postgres@postgres:5432/explorer?sslmode=disable
STANDALONE_DEFAULT_RPC := http://anvil:8545
STANDALONE_DEFAULT_INDEXER := chain-indexer:50051
STANDALONE_DEFAULT_INDEXER_PASSWORD := indexer
STANDALONE_ENV = \
	DATABASE_URL=$${DATABASE_URL:-$(STANDALONE_DEFAULT_DB)} \
	RPC_URL=$${RPC_URL:-$(STANDALONE_DEFAULT_RPC)} \
	INDEXER_URL=$${INDEXER_URL:-$(STANDALONE_DEFAULT_INDEXER)} \
	INDEXER_POSTGRES_PASSWORD=$${INDEXER_POSTGRES_PASSWORD:-$(STANDALONE_DEFAULT_INDEXER_PASSWORD)}

standalone:
	@echo "Starting Block Explorer (standalone — bundled chain-indexer + anvil)..."
	@echo ""
	$(STANDALONE_ENV) docker compose $(STANDALONE_COMPOSE) --profile standalone build
	$(STANDALONE_ENV) docker compose $(STANDALONE_COMPOSE) --profile standalone up -d
	@echo ""
	@echo "Waiting for services..."
	@for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do \
		if curl -s http://127.0.0.1:$(API_PORT)/api/stats >/dev/null 2>&1; then \
			break; \
		fi; \
		sleep 2; \
	done
	@echo ""
	@echo "Block Explorer is ready! (Standalone)"
	@echo ""
	@echo "  Explorer:    http://localhost:$(FRONTEND_PORT)"
	@echo "  API:         http://localhost:$(API_PORT)"
	@echo "  Public API:  http://localhost:$(PUBLIC_API_PORT)"
	@echo ""

standalone-stop:
	@echo "Stopping standalone stack..."
	$(STANDALONE_ENV) docker compose $(STANDALONE_COMPOSE) --profile standalone down -v --remove-orphans
	@echo "Done"

stop:
	@echo "Stopping Block Explorer..."
	docker compose -f docker-compose.yml down -v --remove-orphans
	@echo "Done"

destroy:
	@echo "Destroying Block Explorer (containers, volumes, and images)..."
	docker compose -f docker-compose.yml down -v --remove-orphans --rmi local
	@echo "Done"

logs:
	docker compose -f docker-compose.yml logs -f

rebuild-backend:
	docker compose -f docker-compose.yml build --no-cache api && docker compose -f docker-compose.yml up -d api

# Clean Docker environment (stop services, remove volumes)
clean:
	docker compose down -v --remove-orphans
	docker compose -f docker-compose.dev.yml -f docker-compose.indexer.yml down -v --remove-orphans
	docker system prune -f

# Clean build artifacts
clean-build:
	cd backend && go clean
	rm -rf frontend/.next frontend/node_modules

# =============================================================================
# Version
# =============================================================================

version:
	@echo "Version:    $(VERSION)"
	@echo "Git Rev:    $(GITREV)"
	@echo "Git Branch: $(GITBRANCH)"
	@echo "Build Date: $(DATE)"

# =============================================================================
# CI / Quality
# =============================================================================

lint:
	@echo "--- Backend ---"
	cd backend && go vet ./...
	@echo "--- Frontend ---"
	cd frontend && npx eslint .
	cd frontend && npx tsc -b

test:
	@echo "--- Backend ---"
	cd backend && go test -race -count=1 ./...

build:
	@echo "--- Backend ---"
	cd backend && CGO_ENABLED=0 go build -o /dev/null ./cmd/api
	@echo "--- Frontend ---"
	cd frontend && npm run build

# =============================================================================
# Docker Builds
# =============================================================================

docker-build: docker-build-api docker-build-public-api docker-build-frontend

docker-build-api:
	@echo "Building $(DOCKER_REGISTRY)/$(IMAGE_PREFIX)-api:$(VERSION)"
	docker build -f backend/Dockerfile.api -t $(DOCKER_REGISTRY)/$(IMAGE_PREFIX)-api:$(VERSION) backend/

docker-build-public-api:
	@echo "Building $(DOCKER_REGISTRY)/$(IMAGE_PREFIX)-public-api:$(VERSION)"
	docker build -f backend/Dockerfile.public-api -t $(DOCKER_REGISTRY)/$(IMAGE_PREFIX)-public-api:$(VERSION) backend/

docker-build-frontend:
	@echo "Building $(DOCKER_REGISTRY)/$(IMAGE_PREFIX)-frontend:$(VERSION)"
	docker build -f frontend/Dockerfile -t $(DOCKER_REGISTRY)/$(IMAGE_PREFIX)-frontend:$(VERSION) frontend/

docker-build-dry-run:
	@echo "Docker build dry run (no push)..."
	@echo ""
	@$(MAKE) docker-build-api
	@echo ""
	@$(MAKE)
	@echo ""
	@$(MAKE) docker-build-public-api
	@echo ""
	@$(MAKE) docker-build-frontend
	@echo ""
	@echo "All images built successfully."
