FROM golang:1.25-alpine AS builder

# Upgrade system packages
RUN apk update --no-cache && apk upgrade --no-cache

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /public-api ./cmd/public-api

FROM alpine:3.21

RUN apk update --no-cache && apk upgrade --no-cache
RUN apk --no-cache add ca-certificates libc6-compat

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --from=builder /public-api /public-api

USER appuser:appgroup

ENTRYPOINT ["/public-api"]
