FROM golang:1.25-alpine AS builder

RUN apk update --no-cache && apk upgrade --no-cache && apk add --no-cache git

WORKDIR /app

ENV GOPRIVATE=github.com/gateway-fm/*

COPY go.mod go.sum ./
RUN --mount=type=secret,id=gh_token,required=false \
    if [ -f /run/secrets/gh_token ]; then \
      git config --global url."https://x-access-token:$(cat /run/secrets/gh_token)@github.com/".insteadOf "https://github.com/"; \
    fi && \
    go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /public-api ./cmd/public-api

FROM alpine:3.21

RUN apk update --no-cache && apk upgrade --no-cache
RUN apk --no-cache add ca-certificates libc6-compat

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --from=builder /public-api /public-api

USER appuser:appgroup

ENTRYPOINT ["/public-api"]
