#!/usr/bin/env bash
#
# Generate a .env file with offset host ports for running parallel stacks.
#
# Usage:
#   ./scripts/stack-ports.sh [OFFSET]   # explicit offset (default: auto)
#   ./scripts/stack-ports.sh auto       # derive offset from directory name
#   ./scripts/stack-ports.sh 100        # all base ports + 100
#
# Examples:
#   ./scripts/stack-ports.sh 100 > .env            # Frontend=3101, API=8181, DB=5533, ...
#   ./scripts/stack-ports.sh > .env                 # auto-detect from directory name
#   source <(./scripts/stack-ports.sh 200)          # load into current shell
#
# With no arguments or "auto", the offset is derived from the current directory
# name using a simple hash, yielding a stable value in 100-900 (in steps of 100).

set -euo pipefail

BASE_FRONTEND=3001
BASE_API=8081
BASE_DB=5433
BASE_ANVIL=8546
BASE_PUBLIC_API=8082

auto_offset() {
    # Use the basename of the working directory (typically the worktree name).
    local dir_name
    dir_name="$(basename "$(pwd)")"

    # For the main checkout (common names), offset is 0.
    case "$dir_name" in
        block-explorer|main|master) echo 0; return ;;
    esac

    # Simple hash: sum the bytes of the directory name, mod 9, * 100 -> 100..900
    local sum=0
    local i
    for (( i=0; i<${#dir_name}; i++ )); do
        sum=$(( sum + $(printf '%d' "'${dir_name:$i:1}") ))
    done
    echo $(( (sum % 9 + 1) * 100 ))
}

offset="${1:-auto}"

if [ "$offset" = "auto" ]; then
    offset="$(auto_offset)"
fi

# Validate: must be a non-negative integer
if ! [[ "$offset" =~ ^[0-9]+$ ]]; then
    echo "Error: offset must be a non-negative integer, got '$offset'" >&2
    exit 1
fi

frontend=$(( BASE_FRONTEND + offset ))
api=$(( BASE_API + offset ))
db=$(( BASE_DB + offset ))
anvil=$(( BASE_ANVIL + offset ))
public_api=$(( BASE_PUBLIC_API + offset ))

# Sanity check: ports must be in valid range
for port in "$frontend" "$api" "$db" "$anvil" "$public_api"; do
    if (( port > 65535 )); then
        echo "Error: offset $offset produces port $port which exceeds 65535" >&2
        exit 1
    fi
done

proxy_network="privacy-proxy_proxy-network"
if (( offset != 0 )); then
    proxy_network="${proxy_network}-${offset}"
fi

cat <<EOF
# Generated by scripts/stack-ports.sh (offset=$offset)
FRONTEND_PORT=$frontend
API_PORT=$api
POSTGRES_PORT=$db
ANVIL_PORT=$anvil
PUBLIC_API_PORT=$public_api
PROXY_NETWORK=$proxy_network
EOF
